CREATE TABLE organizers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    pic_name VARCHAR(50) NOT NULL,
    pic_phone_number VARCHAR(20) NOT NULL,
    pic_email TEXT NOT NULL,
    logo_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);